### ISSUE TITLE
Mininum and Maximum are decimals and don't work for Doubles/Longs

### ISSUE THREAD

**Issue by Robulane** [microsoft/OpenAPI.NET#1479]
**Describe the bug**
If the schema has a minimum set to Double.MinValue, the library will crash with the following error

ExceptionType: System.OverflowException
ExceptionMessage:      Value was either too large or too small for a Decimal.
InnerExceptionType:    
InnerExceptionMessage: 
StackTrace: 
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__83_141(OpenApiSchema o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadSchema(ParseNode node)

**Comment by MaggieKimani1** [comment]
Closed by #1480
