### ISSUE TITLE
NullReferenceException when definitions value is null

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/OpenAPI.NET#210]
I realize the example below violates the spec for a couple reasons: (1) I've omitted required sections entirely in order to highlight the issue area, and (2) null value for definitions are not allowed. However, the OpenAPI.NET library should not throw NullReferenceException in any scenario.

**Trimmed down example**
```
{
  "swagger": "2.0",
  "definitions": {
    "Microsoft.UniversalStore.Swagger.Contracts.Metadata.ApiIdentifier": null,
    "Microsoft.UniversalStore.Swagger.Contracts.ApiMetadataStatus": null,
    "Microsoft.UniversalStore.Swagger.Contracts.ApiMetadata": null,
    "Microsoft.UniversalStore.Swagger.FrontDoor.Contracts.V1.Operation": null,
  }
}
```

**NullReferenceException**
```
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadSchema(ParseNode node)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2VersionService.TryLoadReference(ParsingContext context, OpenApiReference reference, IOpenApiReferenceable& referencedObject)
   at Microsoft.OpenApi.Readers.ParsingContext.GetReferencedObject(OpenApiDiagnostic diagnostic, ReferenceType referenceType, String referenceString)
   at Microsoft.OpenApi.Readers.ParseNodes.MapNode.GetReferencedObject[T](ReferenceType referenceType, String referenceId)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__65_87(OpenApiParameter o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadParameter(ParseNode node)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.OpenApi.Readers.ParseNodes.ListNode.CreateList[T](Func`2 map)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__65_53(OpenApiOperation o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadOperation(ParseNode node)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__65_94(OpenApiPathItem o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadPathItem(ParseNode node)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__65_103(OpenApiPaths o, String k, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadPaths(ParseNode node)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__65_12(OpenApiDocument o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadOpenApi(RootNode rootNode)
   at Microsoft.OpenApi.Readers.ParsingContext.Parse(YamlDocument yamlDocument, OpenApiDiagnostic diagnostic)
   at Microsoft.OpenApi.Readers.OpenApiStringReader.Read(String input, OpenApiDiagnostic& diagnostic)
```

**Comment by darrelmiller** [comment]
With my latest PR your example gives me:
> Failed to parse input: Unable to cast object of type 'SharpYaml.Serialization.YamlScalarNode' to type 'SharpYaml.Serialization.YamlMappingNode'.

I suspect it is related to the way reference loading has changed

**Comment by darrelmiller** [comment]
Latest release resolves this issue.
