### ISSUE TITLE
Read Multiple OpenAPISpec for a single service using OpenAPIStringReader

### ISSUE THREAD

**Issue by cvltmaheshp** [microsoft/OpenAPI.NET#507]
Our design has a single service but a lot of endpoints so, to split it up i was searching for some solutions and ended up with the below boilerplate 

https://github.com/dgarcia360/openapi-boilerplate

I was trying to use this and read it out as a single openapidocument object but it was failing with the below error

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'SharpYaml.Serialization.YamlScalarNode' to type 'SharpYaml.Serialization.YamlMappingNode'.
  Source=Microsoft.OpenApi.Readers
  StackTrace:
   at Microsoft.OpenApi.Readers.ParseNodes.MapNode.<>c__DisplayClass7_0`1.<CreateMapWithReference>b__0(KeyValuePair`2 n) in d:\a\1\s\src\Microsoft.OpenApi.Readers\ParseNodes\MapNode.cs:line 112
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in E:\A\_work\258\s\corefx\src\System.Linq\src\System\Linq\Select.cs:line 131
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() in E:\A\_work\258\s\corefx\src\System.Linq\src\System\Linq\Where.cs:line 140
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) in E:\A\_work\258\s\corefx\src\System.Linq\src\System\Linq\ToCollection.cs:line 140
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector) in E:\A\_work\258\s\corefx\src\System.Linq\src\System\Linq\ToCollection.cs:line 100
   at Microsoft.OpenApi.Readers.ParseNodes.MapNode.CreateMapWithReference[T](ReferenceType referenceType, Func`2 map) in d:\a\1\s\src\Microsoft.OpenApi.Readers\ParseNodes\MapNode.cs:line 115
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.<>c.<.cctor>b__102_6(OpenApiComponents o, ParseNode n) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiComponentsDeserializer.cs:line 24
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields) in d:\a\1\s\src\Microsoft.OpenApi.Readers\ParseNodes\PropertyNode.cs:line 41
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiV3Deserializer.cs:line 32
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.LoadComponents(ParseNode node) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiComponentsDeserializer.cs:line 47
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.<>c.<.cctor>b__102_26(OpenApiDocument o, ParseNode n) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiDocumentDeserializer.cs:line 29
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields) in d:\a\1\s\src\Microsoft.OpenApi.Readers\ParseNodes\PropertyNode.cs:line 41
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiV3Deserializer.cs:line 32
   at Microsoft.OpenApi.Readers.V3.OpenApiV3Deserializer.LoadOpenApi(RootNode rootNode) in d:\a\1\s\src\Microsoft.OpenApi.Readers\V3\OpenApiDocumentDeserializer.cs:line 58
   at Microsoft.OpenApi.Readers.ParsingContext.Parse(YamlDocument yamlDocument) in d:\a\1\s\src\Microsoft.OpenApi.Readers\ParsingContext.cs:line 69
   at Microsoft.OpenApi.Readers.OpenApiYamlDocumentReader.Read(YamlDocument input, OpenApiDiagnostic& diagnostic) in d:\a\1\s\src\Microsoft.OpenApi.Readers\OpenApiYamlDocumentReader.cs:line 51
   at Microsoft.OpenApi.Readers.OpenApiTextReaderReader.Read(TextReader input, OpenApiDiagnostic& diagnostic) in d:\a\1\s\src\Microsoft.OpenApi.Readers\OpenApiTextReaderReader.cs:line 53
   at Microsoft.OpenApi.Readers.OpenApiStringReader.Read(String input, OpenApiDiagnostic& diagnostic) in d:\a\1\s\src\Microsoft.OpenApi.Readers\OpenApiStringReader.cs:line 34
   at OpenApiCheck.Program.Main(String[] args) in Program.cs:line 21

Do you support such a split up openapispec ? is there a better way to handle it as having all the endpoints in a single API spec file involves a lot of regression during modifications ?

Code snippet:
string swaggeryaml = System.IO.File.ReadAllText(@"<boilerplatelocation>\src\openapi.yaml"); 
            
var openApiDocument = new OpenApiStringReader(new OpenApiReaderSettings
            {
                ReferenceResolution = ReferenceResolutionSetting.ResolveAllReferences,
                RuleSet = ValidationRuleSet.GetDefaultRuleSet()
            }).Read(swaggeryaml, out var diagnostic);

**Comment by darrelmiller** [comment]
We have a branch where we are working on OpenAPIWorkspace which is a way of loading multiple OpenAPIDocuments into a single workspace that reference each other.  

I'm not sure what issue you are running into.  Maybe if you could share your combined OpenAPI document with me, I can see what problem the reader is running into.

**Comment by cvltmaheshp** [comment]
Hi Darrel,

I was just trying out the OAS example petstore, below is the combined one.

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

I am attaching the seggregated OAS for the above combined petstore yaml
[src.zip](https://github.com/microsoft/OpenAPI.NET/files/4992887/src.zip)

**Comment by cvltmaheshp** [comment]
Darrel, did u get a chance to check this ?

**Comment by darrelmiller** [comment]
I didn't but I will try and look in the the next couple of days.

**Comment by cvltmaheshp** [comment]
Hi Darrel, did u get a chance to look at this ? our service has a lot of APIs and we would like to divide them into multiple swagger file and load it as a workspace to generate some internal files, but since we are not able to do it, we are going with a single swagger file for now hoping you would provide the support :)

**Comment by darrelmiller** [comment]
Hi @cvltmaheshp 

I took a look at this example https://github.com/dgarcia360/openapi-boilerplate/blob/master/src/openapi.yaml  and unfortunately this library is not going to support what you are trying to do there.

As per the OpenAPI specification, $refs are designed to point to single components, not sets of components, or arbitrary chunks of YAML/JSON.  If you are looking to do this, that I would suggest using some kind of pre-processing tool that will merge your files before processing.

**Comment by cvltmaheshp** [comment]
Hi @darrelmiller ,

even if we dont support complete sets, if i have a model in a different yaml and reference that model as an attribute in the main yaml, would that be supported ?

This way we could have the common models moved to a seperate file and a reference could be made to that. when loading main yaml, if there is a possibility to somehow access this external ref, that would also be great. 

for example below can be a common model
IdName:
      title: IdName
      type: object
      description: ''
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true

I might want to reference this from a common.yaml in my main.yaml.
